apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Kustomization

namespace: mealie

components:
  - ../../components/data-guard

resources:
  - deployment.yaml

patches:
  - target:
      kind: Deployment
      name: mealie
    patch: |-
      - op: replace
        path: /spec/template/spec/initContainers/0/volumeMounts/0/mountPath
        value: /app/data
      - op: replace
        path: /spec/template/spec/initContainers/0/env/8/valueFrom/secretKeyRef/name
        value: mealie-infisical-secret
      - op: replace
        path: /spec/template/spec/initContainers/0/env/9/valueFrom/secretKeyRef/name
        value: mealie-infisical-secret
