apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Kustomization

namespace: home-assistant

components:
  - ../../components/data-guard

resources:
  - deployment.yaml

patches:
  - target:
      kind: Deployment
      name: home-assistant
    patch: |-
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: home-assistant
      spec:
        template:
          spec:
            initContainers:
              - name: dataangel
                volumeMounts:
                  - name: config
                    mountPath: /config
                env:
                  - name: AWS_ACCESS_KEY_ID
                    valueFrom:
                      secretKeyRef:
                        name: home-assistant-infisical-secret
                  - name: AWS_SECRET_ACCESS_KEY
                    valueFrom:
                      secretKeyRef:
                        name: home-assistant-infisical-secret
