apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Kustomization

namespace: home-assistant

components:
  - ../../components/data-guard

resources:
  - deployment.yaml

patches:
  - target:
      kind: Deployment
      name: home-assistant
    patch: |-
      - op: replace
        path: /spec/template/spec/initContainers/0/volumeMounts/0/name
        value: config
      - op: replace
        path: /spec/template/spec/initContainers/0/volumeMounts/0/mountPath
        value: /config
      - op: replace
        path: /spec/template/spec/initContainers/0/env/8/valueFrom/secretKeyRef/name
        value: home-assistant-infisical-secret
      - op: replace
        path: /spec/template/spec/initContainers/0/env/9/valueFrom/secretKeyRef/name
        value: home-assistant-infisical-secret
